
version: '3.8'

services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"  # Porta do DNS
      - "2222:22"    # Mapeia a porta 2222 do host para a porta 22 do contêiner (SSH)
    environment:
      - PASSWORD_AUTH=yes  # Variável para controle de autenticação por senha (se necessário)
    command: /usr/sbin/sshd -D  # Comando para iniciar o SSH no contêiner


  proxy:
    build:
      context:  ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
    networks:
      - asa-network

  asa-server:
    build:
      context:  ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-network

  asa-server2:
    build:
      context:  ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server2
    networks:
      - asa-network

  asa-server02:
    build:
      context:  ./asa-server02
      dockerfile: Dockerfile
    container_name: asa-server02
    ports:
      - "8080:80/tcp"
    networks:
      - asa-network

  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: email
    ports:
      - "25:25/tcp"  # SMTP
      - "110:110/tcp"  # POP3
      - "587:587/tcp"  # SMTP com cliente
      - "143:143/tcp"  # IMAP
    volumes:
      - emailvol:/etc/mail  # Mapeando o volume 'emailvol' para configuração do email
      - ./email:/etc/mail  # Mapeando o diretório local './email' para configuração do email
      - email_data:/var/spool/mail  # Persistindo mensagens de email
    networks:
      - asa-network

networks:
  asa-network:
    driver: bridge

volumes:
  emailvol:
  email_data:
