version: '3.8'

services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "2222:22"
    environment:
      - PASSWORD_AUTH=yes
    networks:
      - asa-network
      - shared-network 

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "443:443/tcp"
      - "2223:22"
    depends_on:
      - wordpress
      - webmail
    networks:
      - asa-network
      - shared-network 
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress_db
    networks:
      - asa-network
      - shared-network 

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    ports:
      - "8081:80"  # Corrigido: Adicione a porta do host (ex: 8081)
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress1
    depends_on:
      - wordpress_db
    volumes:
      - wordpress1_data:/var/www/html
    networks:
      - asa-network
      - shared-network 

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    ports:
      - "8082:80"  # Corrigido: Adicione a porta do host (ex: 8082)
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress2
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress2
    depends_on:
      - wordpress_db
    volumes:
      - wordpress2_data:/var/www/html
    networks:
      - asa-network
      - shared-network 









 # wordpress3:
  #  image: wordpress:latest
  #  container_name: wordpress3
  #  ports:
  #    - "8083:80"  # Corrigido: Adicione a porta do host (ex: 8081)
  #  restart: always
  #  environment:
  #    WORDPRESS_DB_HOST: wordpress_db
  #    WORDPRESS_DB_USER: wordpress3
  #    WORDPRESS_DB_PASSWORD: senha123
  #    WORDPRESS_DB_NAME: wordpress3
  #  depends_on:
  #    - wordpress_db
  #  volumes:
  #    - wordpress3_data:/var/www/html
  #  networks:
  #    - asa-network

 # wordpress4:
 #   image: wordpress:latest
 #   container_name: wordpress4
 #   ports:
  #    - "8084:80"  # Corrigido: Adicione a porta do host (ex: 8082)
  #  restart: always
  #  environment:
  #    WORDPRESS_DB_HOST: wordpress_db
  #    WORDPRESS_DB_USER: wordpress4
  #    WORDPRESS_DB_PASSWORD: senha123
  #    WORDPRESS_DB_NAME: wordpress4
  #  depends_on:
  #    - wordpress_db
  #  volumes:
  #    - wordpress4_data:/var/www/html
  #  networks:
  #    - asa-network
 








  wordpress_db:
    image: mariadb:10.6
    restart: always
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wordpress_db_data:/var/lib/mysql
      - ./webmail/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - asa-network
      - shared-network 

  nextcloud:
    image: nextcloud:latest
    restart: always
    container_name: nextcloud
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: SenhaSegura123
      MYSQL_HOST: nextcloud_db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_password
    depends_on:
      - nextcloud_db
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud/config:/var/www/html/config
    networks:
      - asa-network
      - shared-network 

  nextcloud_db:
    image: mariadb:10.6
    restart: always
    container_name: nextcloud_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - asa-network
      - shared-network 

  webmail:
    container_name: webmail
    build:
      context: ./webmail
      dockerfile: Dockerfile
    ports:
      - "25:25/tcp"
      - "465:465/tcp"
      - "587:587/tcp"
      - "143:143/tcp"
      - "993:993/tcp"
      - "110:110/tcp"
      - "995:995/tcp"
      - "2224:22/tcp"
    volumes:
      - emailvol:/etc/mail
      - email_data:/var/spool/mail
      #- dovecot_data:/etc/dovecot/private
    networks:
      - asa-network
      - shared-network 

networks:
  asa-network:
    driver: bridge
  shared-network:
    external: true

volumes:
  wordpress_data:
  wordpress_db_data:
  wordpress1_data:
  wordpress2_data:
  #wordpress3_data:
  #wordpress4_data:
  nextcloud_data:
  nextcloud_db_data:
  emailvol:
  email_data:

 


 

 
 
