version: '3.8'

services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "2222:22"
    environment:
      - PASSWORD_AUTH=yes
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      #- "80:80/tcp"
      - "443:443/tcp"
      - "2223:22"
    depends_on:
      - wordpress                                                     
      - webmail
    networks:
      - asa-network
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
     

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - asa-network

  wordpress1:   
    image: wordpress:latest
    container_name: wordpress1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress1
    volumes:
      - wordpress1_data:/var/www/html
    networks:
      - asa-network

  wordpress2:   
    image: wordpress:latest
    container_name: wordpress2
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress2
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress2
    volumes:
      - wordpress2_data:/var/www/html
    networks:
      - asa-network







  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - webmail
      - db
    environment:
      ROUNDCUBE_DB_TYPE: mysql
      ROUNDCUBE_DB_HOST: db
      ROUNDCUBE_DB_USER: roundcube
      ROUNDCUBE_DB_PASSWORD: roundcube
      ROUNDCUBE_DB_NAME: roundcube
      ROUNDCUBE_DEFAULT_HOST: tls://webmail
      ROUNDCUBE_SMTP_SERVER: tls://webmail
    volumes:
      - roundcube_data:/var/www/html
    networks:
      - asa-network

  

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asa-network


  webmail:
    build:
      context:  ./webmail
      dockerfile: Dockerfile
    container_name: webmail
    ports:
     - "25:25/tcp"        # SMTP (não criptografado)
     - "465:465/tcp"      # SMTPS (SMTP sobre SSL)
     - "587:587/tcp"      # SMTP Submission (STARTTLS)
     - "143:143/tcp"      # IMAP (não criptografado)
     - "993:993/tcp"      # IMAPS (IMAP sobre SSL)
     - "110:110/tcp"      # POP3 (não criptografado)
     - "995:995/tcp"      # POP3S (POP3 sobre SSL)
     - "22:22/tcp"
    volumes:
    - emailvol:/etc/mail  # Mapeando o volume 'emailvol' para o diretório /etc/mail no container
    - email_data:/var/spool/mail  # Mapeando o volume 'email_data' para o diretório /var/spool/mail (para persistir mensagens) 
    - dovecot_data:/etc/dovecot/private
    
    
    networks:
      - asa-network


networks:
  asa-network:
    driver: bridge

volumes:
  wordpress_data:
  mysql_data:
  maildata:
  mailstate:
  mailconfig:
  emailvol: 
  email_data:  
  dovecot_data:
  roundcube_data:
  wordpress1_data:
  wordpress2_data:


 
 
