version: '3.8'

services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "2222:22"
    environment:
      - PASSWORD_AUTH=yes
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "443:443/tcp"
      - "2223:22"
    depends_on:
      - wordpress
      - webmail
    networks:
      - asa-network
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - nextcloud_db
    networks:
      - asa-network

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress1
    volumes:
      - wordpress1_data:/var/www/html
    networks:
      - asa-network

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress2
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wordpress2
    volumes:
      - wordpress2_data:/var/www/html
    networks:
      - asa-network

  nextcloud:
    image: nextcloud:latest
    restart: always
    container_name: nextcloud
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: SenhaSegura123 
      MYSQL_HOST: nextcloud_db  
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_password
    depends_on:
      - nextcloud_db
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud/config:/var/www/html/config
    networks:
      - asa-network

  nextcloud_db:
    image: mariadb:10.6
    restart: always
    container_name: nextcloud_db
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - nextcloud_db_data:/var/lib/mysql 
    networks:
      - asa-network

  webmail:
    container_name: webmail
    build:
      context: ./webmail
      dockerfile: Dockerfile
    ports:
      - "25:25/tcp"
      - "465:465/tcp"
      - "587:587/tcp"
      - "143:143/tcp"
      - "993:993/tcp"
      - "110:110/tcp"
      - "995:995/tcp"
      - "22:22/tcp"
    volumes:
      - emailvol:/etc/mail
      - email_data:/var/spool/mail
      - dovecot_data:/etc/dovecot/private
    networks:
      - asa-network

networks:
  asa-network:
    driver: bridge

volumes:
  wordpress_data:
  mysql_data:
  maildata:
  mailstate:
  mailconfig:
  emailvol:
  email_data:
  dovecot_data:
  wordpress1_data:
  wordpress2_data:
  nextcloud_data:
  nextcloud_db_data:


 
 
