# Usar a imagem base do Ubuntu
FROM ubuntu:latest


RUN apt update && apt install -y \
    bind9 \
    dnsutils \
    openssh-server \
    sudo \
    curl






RUN mkdir /var/run/sshd

# criar o usuário "dns" e definir a senha
RUN useradd -m -s /bin/bash dns && \
    echo 'dns:senha123' | chpasswd && \
    usermod -aG sudo dns

#permitir autenticação por senha e desabilitar o login do root
RUN sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config


RUN mkdir -p /home/dns/.ssh && \
    chown -R dns:dns /home/dns/.ssh && \
    chmod 700 /home/dns/.ssh









COPY named.conf.local /etc/bind/named.conf.local
COPY zones/ /etc/bind/zones/


EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 22/tcp


CMD /usr/sbin/sshd -D & /usr/sbin/named -g && tail -f /dev/null