FROM ubuntu:latest

# Atualiza o sistema e instala pacotes necessários
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    postfix \
    dovecot-core \
    dovecot-imapd \
    dovecot-pop3d \
    syslog-ng \
    openssl \
    openssh-server \
    apache2 \
    php \
    php-cli \
    php-mysql \
    php-curl \
    php-json \
    php-xml \
    php-mbstring \
    unzip \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Criação de usuários
RUN groupadd -f -r adm && \
    useradd -r -g adm -u 999 syslog

RUN useradd -m pipa && \
    useradd -m pontanegra && \
    useradd -m genipabu && \
    echo "pipa:redes" | chpasswd && \
    echo "pontanegra:redes" | chpasswd && \
    echo "genipabu:redes" | chpasswd



RUN echo "subjectAltName=DNS:genipabu.com.br,DNS:pipa.com.br,DNS:pontanegra.br" >> /etc/ssl/openssl.cnf

RUN mkdir -p /var/log/mail && \
    touch /var/log/mail.log && \
    chmod 666 /var/log/mail.log






RUN mkdir /var/run/sshd

    # criar o usuário "dns" e definir a senha
RUN useradd -m -s /bin/bash webmail && \
    echo 'webmail:senha123' | chpasswd && \
    usermod -aG sudo webmail
    
  
RUN sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    
    
RUN mkdir -p /home/webmail/.ssh && \
    chown -R webmail:webmail /home/webmail/.ssh && \
    chmod 700 /home/webmail/.ssh
    






# Copia os arquivos de configuração do Postfix, Dovecot e Syslog-NG
COPY main.cf /etc/postfix


COPY master.cf /etc/mail/master.cf



# Exposição de portas
EXPOSE 25/tcp 143/tcp 587/tcp 993/tcp 80/tcp 22/tcp

# Comando de inicialização
#CMD ["sh", "-c", "service syslog-ng start ; service postfix start ; service dovecot start; service apache2 start; tail -F /var/log/mail.log; service ssh start && nginx -g 'daemon off"]

#CMD ["sh", "-c", "service syslog-ng start; service postfix start; service dovecot start; service apache2 start; tail -F /var/log/mail.log; service ssh start; nginx -g 'daemon off'"]
CMD ["sh", "-c", "service syslog-ng start; service postfix start; service dovecot start; service apache2 start; service ssh start; tail -F /var/log/mail.log; nginx -g 'daemon off'"]


##comandos testar###
#telnet "ip" 25             
#helo mail.asa.br
#mail from: bob@asa.br
#rcpt to: patrick@asa.br
#data
#oi este é um email
#quit

#OU telnet "ip" 110
#comando para pop:
#user bob
#list




##VER LOGS DE EMAILS (cada arquivo é a caixa de email de cada usuario)
#docker exec -it email /bin/bash 
#cd /var/spool/mail
#ls -la
##os emails novos que estao chegando sao colocados no inicio do arquivo




##comandos testar###
#telnet "ip" 25             
#helo mail.asa.br
#mail from: bob@asa.br
#rcpt to: patrick@asa.br
#data
#oi este é um email
#quit

#OU telnet "ip" 110
#comando para pop:
#user bob
#list




##VER LOGS DE EMAILS (cada arquivo é a caixa de email de cada usuario)
#docker exec -it email /bin/bash 
#cd /var/spool/mail
#ls -la
##os emails novos que estao chegando sao colocados no inicio do arquivo




