# Usar a imagem base do Ubuntu
FROM ubuntu:latest

# Atualizar repositório e instalar pacotes necessários


RUN apt update && apt install -y \
    bind9 \
    dnsutils \
    openssh-server \
    sudo \
    curl

# Criar um diretório necessário para o SSH
RUN mkdir /var/run/sshd

# Criar um usuário (substitua "usuario" por um nome de sua escolha)
RUN useradd -m -s /bin/bash usuario

# Definir uma senha para o usuário (substitua "senha123" por uma senha segura)
RUN echo 'usuario:senha123' | chpasswd

# Adicionar o usuário ao grupo sudo (para que ele tenha permissões elevadas, se necessário)
RUN usermod -aG sudo usuario

# Configurar o SSH: permitir autenticação por senha e desabilitar o login do root
RUN sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
RUN sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Garantir que a chave SSH do usuário seja criada
RUN mkdir -p /home/usuario/.ssh && chown -R usuario:usuario /home/usuario/.ssh

# Copiar arquivos de configuração do BIND
COPY named.conf.local /etc/bind/named.conf.local
#COPY db.com.br /etc/bind/db.com.br
COPY zones/ /etc/bind/zones/


# Expor as portas necessárias
EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 22/tcp  

# Iniciar o BIND e o SSH
#CMD service ssh start && /usr/sbin/named -g -c /etc/bind/named.conf -u bind && tail -f /dev/null

#CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
CMD /usr/sbin/sshd -D & /usr/sbin/named -g && tail -f /dev/null

