FROM nginx:latest


RUN apt update && apt install -y \
    openssh-server \
    vim \
    curl




# Criar um diretório necessário para o SSH
RUN mkdir /var/run/sshd

# Criar o usuário "proxy" e definir a senha
RUN useradd -m -s /bin/bash proxy1 && \
    echo 'proxy1:senha123' | chpasswd && \
    usermod -aG sudo proxy1

# Configurar o SSH: permitir autenticação por senha e desabilitar o login do root
RUN sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Garantir que a chave SSH do usuário seja criada
RUN mkdir -p /home/proxy1/.ssh && \
    chown -R proxy1:proxy1 /home/proxy1/.ssh && \
    chmod 700 /home/proxy1/.ssh

# Copiar arquivos de configuração do Nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/
COPY ssl/ /etc/nginx/ssl/

# Expor as portas para HTTP (80), HTTPS (443) e SSH (22)
EXPOSE 80 443 22


CMD ["sh", "-c", "service ssh start && nginx -g 'daemon off;'"]